import { callGemini, parseJsonResponse } from './gemini.js'

const DOCTOR_SUMMARY_PROMPT = (data) => `
You are an experienced physician preparing a clinical summary.

Patient Information:
- Name: ${data.patientName}
- Age: ${data.age}
- Gender: ${data.gender}
- Weight: ${data.weightKg} kg
- Height: ${data.heightCm} cm

Lifestyle:
- Average calories/day: ${data.avgCalories}
- Average sleep/night: ${data.avgSleep} hours
- Active days in last 30 days: ${data.activeDays}

Medical History:
- Conditions: ${data.conditions}
- Allergies: ${data.allergies}
- Medications: ${data.medications}

Abnormal Lab Findings:
${JSON.stringify(data.abnormalLabs, null, 2)}

Instructions:
1. Write a concise summary for a doctor visit.
2. Highlight clinically relevant abnormalities.
3. Mention lifestyle concerns.
4. Mention possible areas for follow-up.
5. Do NOT provide definitive diagnoses.
6. Use professional medical language.

End with: "This summary was auto-generated by ArogyaAI and should not replace professional medical evaluation."

Return ONLY valid JSON:

{
  "summary": "...",
  "generatedAt": "${new Date().toISOString()}",
  "keyFindings": [
    "finding 1",
    "finding 2"
  ],
  "recommendations": [
    "recommendation 1",
    "recommendation 2"
  ]
    
}
`

export async function generateDoctorSummary(summaryData) {
    if (!summaryData || typeof summaryData !== 'object') {
        throw new Error('Invalid summary data provided')
    }

    const prompt = DOCTOR_SUMMARY_PROMPT(summaryData)
    const response = await callGemini(prompt)
    const result = parseJsonResponse(response)

    
    if (!result.summary || typeof result.summary !== 'string') {
  throw new Error('Invalid doctor summary response')
}

result.keyFindings ??= []
result.recommendations ??= []

    return result
}

export function formatSummaryData(profile, user, metrics, medicines, labValues) {
    return {
        patientName: user?.name || 'Unknown',
        age: profile?.age || 'N/A',
        gender: profile?.gender || 'N/A',
        weightKg: profile?.weightKg || 'N/A',
        heightCm: profile?.heightCm || 'N/A',
        avgCalories: metrics.avgCalories,
        avgSleep: metrics.avgSleep,
        activeDays: metrics.activeDays,
        medications: medicines.length > 0
            ? medicines.map(m => `${m.name} (${m.dose})`).join(', ')
            : 'None',
        labValues: labValues.length > 0
            ? labValues.map(l => `${l.parameter}: ${l.value} ${l.unit}`).join(', ')
            : 'None',
        conditions: profile?.conditions?.length > 0
            ? profile.conditions.join(', ')
            : 'None reported',
        allergies: profile?.allergies?.length > 0
            ? profile.allergies.join(', ')
            : 'None reported',
        abnormalLabs: labValues
            .filter(l => l.isAbnormal)
            .map(l => ({
                parameter: l.parameter,
                value: l.value,
                unit: l.unit,
                referenceRange: l.referenceRange
            })),
    }
}

export function calculateMetrics(meals, sleepLogs, activities) {
    return {
        avgCalories: meals.length
            ? (meals.reduce((s, m) => s + m.calories, 0) / meals.length).toFixed(0)
            : 0,
        avgSleep: sleepLogs.length
            ? (sleepLogs.reduce((s, l) => s + l.hours, 0) / sleepLogs.length).toFixed(1)
            : 0,
        activeDays: new Set(activities.map(a => a.date.toISOString().split('T')[0])).size
    }
}